### ISSUE TITLE
[1.16.1] Lava Bucket Gets Deleted on turtle.placeDown()

### ISSUE THREAD

**Issue by Flexico** [SquidDev-CC/CC-Tweaked#530]
I have a program that has a turtle go out over a lava lake and fill buckets in its inventory. If there's a stack of at least 2, it works properly, but if it only has one empty bucket and it picks up a lava source block, the lava disappears but no lava bucket appears in the inventory, and the bucket gets deleted.

I found a couple of closed issues involving buckets and liquids, but I'm pretty sure this is a different thing, or at least a persistent problem. Thanks for your time!

**Comment by SquidDev** [comment]
Can you update to the 1.16.2 version of CC:T and try again? There were several bugs fixed in that version relating to item placing.

**Comment by Flexico** [comment]
Does Forge for 1.16.2 still have that problem with the turtles and Optifine?

**Comment by theghouse** [comment]
I can confirm that lava and bucket related issues appear to be resolved in the 1.16.2 version.  However, there are still some issues with water and buckets.  

I'm not very familiar with the github interface, I left more detailed comments on closed issue #518 however it did not reopen the issue.

**Comment by Flexico** [comment]
Yep, it works properly in 1.16.2! Thanks a bunch~

**Comment by prozacgod** [comment]
I've been playing in a 16.2 modpack with "cc-tweaked-fabric-1.16.2-1.91.1.jar" which looks to be from "Sep 4, 2020"

I had this issue in both smp/ssp

I think the 16.2 version is cc:restitched, I'm not sure if it's appropriate to post about that version here or not as I can't figure out if it's related to this project direction or indirectly - appologies if this is the wrong place to post.
